# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Halo < Formula
  desc "Halo compliance platform CLI"
  homepage "https://github.com/halo-compliance/cli"
  version "0.1.0"
  license "UNLICENSED"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/halo-compliance/cli/releases/download/v0.1.0/halo_darwin_amd64.tar.gz"
      sha256 "30aad9214415bc01053ad7fcb85dacc061f3d20d3323a79591f44339acafab2f"

      define_method(:install) do
        bin.install "halo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/halo-compliance/cli/releases/download/v0.1.0/halo_darwin_arm64.tar.gz"
      sha256 "6a7d383f070dd4406dbfb9534865fae23d83b251a0a230192c08db7d596bc0f3"

      define_method(:install) do
        bin.install "halo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/halo-compliance/cli/releases/download/v0.1.0/halo_linux_amd64.tar.gz"
      sha256 "aae62d5fb11560d842c840369edf2bb399aaeb5a401135cb1a064a99c6e01f56"
      define_method(:install) do
        bin.install "halo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/halo-compliance/cli/releases/download/v0.1.0/halo_linux_arm64.tar.gz"
      sha256 "0e6b1710b17ebbd1ce44060d6ef5356ce4c2497835ff792be3b51dfff4971837"
      define_method(:install) do
        bin.install "halo"
      end
    end
  end

  test do
    system "#{bin}/halo", "--version"
  end
end
