# This file was generated by GoReleaser. DO NOT EDIT.
cask "halo" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "eb07b6d2bc8a11ed9d062184f755d4172b6e97e74ca2b5f54dfd958093997110"
      url "https://halo-compliance-cli-releases.s3.us-east-1.amazonaws.com/#{version}/halo_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e6b7a8d93fe965271e71c7ace1037b1e8611bf0fccde414aaf14fc8ec4cb7648"
      url "https://halo-compliance-cli-releases.s3.us-east-1.amazonaws.com/#{version}/halo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3db4ea12f327624c631faaec3e90d8511197d576e1034b10045d4e266fbe4dd8"
      url "https://halo-compliance-cli-releases.s3.us-east-1.amazonaws.com/#{version}/halo_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cfc8521ade8753c7e0669d5b5e897140838a3b35083b45b64301c702b1868104"
      url "https://halo-compliance-cli-releases.s3.us-east-1.amazonaws.com/#{version}/halo_linux_arm64.tar.gz"
    end
  end

  name "halo"
  desc "Halo compliance platform CLI"
  homepage "https://github.com/halo-compliance/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "halo"

  # No zap stanza required

end
